chore: Setup project layout
foxssake/dumber-dungeons pull request #33
Opened 2024-11-27 14:26 UTC by elementbound

Closes #15

2024-11-27 14:28 UTC, elementbound commented on bun.lockb
Turns out `bun.lockb` is really a pain in the butt when moving between branches and PRs, and we can just use pinned version instead for reproducible builds.

2024-11-27 14:28 UTC, elementbound commented on package.json
> +    "format": "prettier --write \"packages/*src/**/*.ts\" \"packages/*/test/**/*.ts\"",
Figured we could have these in the root package, since these apply to all packages. And we'd run these for all packages anyway from CI.

2024-11-27 15:04 UTC, elementbound commented
Note to self: update attributions as files have moved a bunch

2024-11-28 16:11 UTC, ocsi0520 commented
- nest-cli.json should be moved into **Server** package
- What about eslint.config.mjs? I thought we are going to move it under **Shared** folder
- Do we still need this `public/build` folder?
- Can we rename `mocks` folder? This term is too overloaded, and I'd preferer `UI-Wireframe` or `Sketches` or `Drafts` or sg like that

2024-11-28 16:18 UTC, ocsi0520 requested changes

2024-11-28 16:21 UTC, ocsi0520 commented on package.json
> +    "format": "prettier --write \"packages/*src/**/*.ts\" \"packages/*/test/**/*.ts\"",
On the other hand whenever I'm working only on one of the packages, maybe I don't want to format all of them.
So maybe this could be just an aggregation of the `format` commands from all of the packages.

But just a suggestion, either way I'm good with it. :smile:

2024-11-28 16:36 UTC, elementbound commented on package.json
> +    "format": "prettier --write \"packages/*src/**/*.ts\" \"packages/*/test/**/*.ts\"",
> maybe I don't want to format all of them

Why not? :smile: Anyway, my issue is duplicating these commands in all the packages, so I'd prefer to keep them this way.

2024-11-28 17:30 UTC, elementbound commented on package.json
> +    "format": "prettier --write \"packages/*src/**/*.ts\" \"packages/*/test/**/*.ts\"",
nvm, ended up giving configs to all packages, and doing aggregate scripts with `bun --filter`

2024-11-28 17:44 UTC, elementbound commented on packages/shared/prettier.config.mjs
Maybe we could export this, so this way the other packages could just depend on `@dumber-dungeons/shared`@`workspace:*` and import the configs, instead of referring to paths.

2024-11-28 20:22 UTC, ocsi0520 approved these changes

2024-11-28 20:24 UTC, elementbound commented on packages/shared/prettier.config.mjs
TODO in #35

2024-11-28 20:24 UTC, merged