chore: Integrate stack
foxssake/dumber-dungeons pull request #36
Opened 2024-11-29 14:30 UTC by elementbound

Integrates the frontend setup in #34 with the backend setup in #31 by building the frontend into a shared directory.

2024-11-29 14:32 UTC, elementbound commented
@ocsi0520 I've ended up leaving the `packages/client/public` directory in-tact, that's where we can store static assets to be served. Let me know if you have any recommendations on changing it.

2024-12-07 11:12 UTC, ocsi0520 requested changes

2024-12-07 11:13 UTC, ocsi0520 commented
Please use `npm run lint`

2024-12-07 11:15 UTC, elementbound commented on packages/server/src/view.service.ts
> +import { join, resolve } from 'path';
I do, this prints a warning. I don't see any other way to manipulate file paths reliably, let me know if you have a good alternative.

2024-12-07 11:16 UTC, elementbound commented on packages/client/scripts/build.ts
> +    const mainFile = tsxFiles[0];
Ideally, there's only one tsx file, in which case it will be the main one. If there's more, we can't be sure, so a warning is printed.

2024-12-07 11:18 UTC, elementbound commented on packages/client/scripts/build.ts
> +    result.logs.forEach((log) => {
IIRC that's not the same - The forEach method passes in the item, index, and the whole array. So using console.log would print more than the log message per line. Example:
![image](https://github.com/user-attachments/assets/1431f206-aa44-40fb-93d7-aa50e5bbada4)

2024-12-07 11:21 UTC, elementbound commented on packages/client/scripts/build.ts
> +    const htmlData = templateData.replaceAll('{main}', `${view.name}.js`);
I ended up using `.replaceAll` out of principle. If we treat this as substituting the right path to the single `<script>` tag, then `.replace` would suffice. I treated this as substituting a template variable to a template string, in which case `.replaceAll` makes more sense.

Either way, let me know if you'd like this to be changed. In practice it wouldn't make sense to have multiple `{main}`'s in the template as of now.

2024-12-07 11:22 UTC, elementbound commented on packages/client/scripts/serve.ts
> +async function globScan(
The intent was to keep each script separate and self-contained, but we can introduce a `scripts/shared.ts` for these. What do you think?

2024-12-07 19:01 UTC, ocsi0520 commented on packages/client/scripts/build.ts
> +    const mainFile = tsxFiles[0];
But that's a warning, not an error which causes to stop the process.
So it's not deterministic, not testable, not foreseeable.

AFAIR, we talked about having a `main.tsx` in every view, so the string "main" could be used in order to determine which one is the main.

2024-12-07 19:05 UTC, ocsi0520 commented on packages/client/scripts/serve.ts
> +async function globScan(
TBH I heard many times to "keep sg separate & self-contained" but in the end we just had a lot of duplications.
It's totally fine to keep them away from each other (I mean no import between serve.ts <--> build.ts),
but if there's a piece of code which is the same (and not just character by character but the logic that you want to do)
then you should extract it IMHO

2024-12-07 19:07 UTC, ocsi0520 commented on packages/client/scripts/build.ts
> +    const htmlData = templateData.replaceAll('{main}', `${view.name}.js`);
Actually you are right, if in the template we have the same {variable} we should replace all of them with the same content.
For me a simple extra comment is enough to say that theoretically we should have only one variable which is called _main_

2024-12-07 19:26 UTC, ocsi0520 commented on packages/client/scripts/build.ts
> +    result.logs.forEach((log) => {
you are totally right, my bad

2024-12-07 19:33 UTC, ocsi0520 commented on packages/server/src/view.service.ts
> +import { join, resolve } from 'path';
Rule: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-nodejs-modules.md
> Forbid the use of Node.js builtin modules. Can be useful for client-side web projects that do not have access to those modules.

> When Not To Use It
If you have a project that is run mainly or partially using Node.js.

So what I suggest is to disable it in server side :smile:

2024-12-08 21:47 UTC, elementbound commented on packages/server/src/view.service.ts
> +const packageRoot = resolve(join(import.meta.dir, '../'));
Moved path declarations into a module, so now they can be injected wherever needed.

2024-12-08 21:48 UTC, elementbound commented on packages/server/src/view.service.ts
> +import { join, resolve } from 'path';
Disabled! ( Respectfully )

2024-12-08 21:48 UTC, elementbound commented on packages/client/scripts/build.ts
> +    void Bun.write(targetPath, Bun.file(sourcePath));
Done, build will now fail on write errors.

2024-12-08 21:48 UTC, elementbound commented on packages/client/scripts/build.ts
> +    const tsxFiles = await globScan('*.tsx', { cwd: viewDir }).catch(() => []);
Removed catch; if there's an error, the build should fail.

2024-12-08 21:49 UTC, elementbound commented on packages/client/scripts/build.ts
> +    const mainFile = tsxFiles[0];
Went with `<view name>.tsx` - otherwise we'd have a bunch of `main.tsx` files, which would make it difficult to navigate editor tabs and such.

2024-12-08 21:50 UTC, elementbound commented on packages/client/scripts/build.ts
> +  for (const viewDir of viewDirectories) {
Felt like extracting would add an unnecessary extra step for the reader, and the operations don't map nicely to array operations, so left as-is.

2024-12-08 21:50 UTC, elementbound commented on packages/client/scripts/build.ts
> +    console.error('Failed building views:\n', failedViews.join('\n'));
Fixed.

2024-12-08 21:50 UTC, elementbound commented on packages/client/scripts/build.ts
> +if (isWatching) {
Good catch! Done.

2024-12-08 21:51 UTC, elementbound commented on packages/client/scripts/build.ts
> +async function build(): Promise<void> {
We can and we did!

2024-12-08 21:51 UTC, elementbound commented on packages/client/scripts/build.ts
> +    const htmlData = templateData.replaceAll('{main}', `${view.name}.js`);
Added comment.

2024-12-08 21:51 UTC, elementbound commented on packages/client/scripts/serve.ts
> +async function globScan(
Fair point, extracted shared parts into `shared.ts`.

2024-12-08 21:51 UTC, elementbound commented on packages/client/scripts/serve.ts
> +const views = (await globScan('*.html', { cwd: viewRoot })).map((path) =>
Done.

2024-12-08 21:53 UTC, elementbound commented on packages/client/scripts/serve.ts
> +    const view = Bun.file(join(viewRoot, `${urlPath}.html`));
In ambigious cases, views enjoy precedence. This shouldn't happen though - you'd need an asset with the exact same name as the view name - e.g. a view called `threejs` and an asset called `threejs`. If this happens, we've done something wrong :slightly_smiling_face:

2024-12-09 09:30 UTC, ocsi0520 commented on packages/server/src/view.service.ts
> +const packageRoot = resolve(join(import.meta.dir, '../'));
What about this:
![image](https://github.com/user-attachments/assets/58b1e8fe-610a-4537-a22c-5d44b51925f2)

So that:
- I don't have to lookup the strings in paths.module.ts (or know it by heart)
- In case I need multiple folders, I don't have to litter my constructor

In case we put PathService into AppModule, we don't even have to deal with importing into a module.
Moreover I don't see path constants as a separate module.

2024-12-09 09:49 UTC, ocsi0520 commented on packages/client/scripts/build.ts
> +    const mainFile = tsxFiles[0];
> ...in case of a build (especially a prod build), I expect from the process if anything fails it should not emit files
Please throw an error in case we don't have the necessary file structure

2024-12-09 11:17 UTC, ocsi0520 commented on packages/client/scripts/build.ts
> +  const htmlData = templateData.replaceAll('{main}', mainPath);
I just realized, that basically you insert the URL of the main.js.
Can we rename the {main} to {mainJsURL}? (Or sg similar)

2024-12-09 11:24 UTC, ocsi0520 commented on packages/client/scripts/build.ts
> +  await Bun.write(templateWritePath, htmlData);
Also realized that buildView is not complied with CQS. (That's not necessary a problem).
Do we want to have separate function where we just get the "build result" (isSuccessful + build code), and then we write the files in a separate one?

IMHO that would be better, because in case we have any failed build, then we just show the errors.
If not, we write the files.

So we don't end up with a mixed files from the prev and the current built.
(I.e. `module A` could be built this time and the prev one, while `module B` could built only in the prev one
in this case `module A` is written, but `module B`'s remnant from the prev is still there)

2024-12-09 11:40 UTC, ocsi0520 commented on packages/client/scripts/shared.ts
> +/* eslint-disable import-x/no-nodejs-modules */
Optional: create a separate `eslint.config.mjs` inside _scripts_ folder, and basically copy-paste the server's config

2024-12-16 21:39 UTC, elementbound commented on packages/server/src/view.service.ts
> +const packageRoot = resolve(join(import.meta.dir, '../'));
Created ContentService instead to handle this.

2024-12-16 21:39 UTC, elementbound commented on packages/client/scripts/build.ts
> +    const mainFile = tsxFiles[0];
Resolving as change was removed.

2024-12-16 21:40 UTC, elementbound commented on packages/client/scripts/build.ts
> +  const htmlData = templateData.replaceAll('{main}', mainPath);
Resolving as change was removed.

2024-12-16 21:40 UTC, elementbound commented on packages/client/scripts/build.ts
> +      console.error(`Couldn't build "${view.name}"!\n`, result.logs, '\n');
Resolving as change was removed.

2024-12-16 21:40 UTC, elementbound commented on packages/client/scripts/build.ts
> +  await Bun.write(templateWritePath, htmlData);
Resolving as change was removed.

2024-12-16 21:40 UTC, elementbound commented on packages/client/scripts/shared.ts
> +/* eslint-disable import-x/no-nodejs-modules */
Resolving as change was removed.

2024-12-18 16:08 UTC, ocsi0520 requested changes

2024-12-18 16:08 UTC, ocsi0520 commented on packages/server/src/main.ts
> +  const contentService = app.get(ContentService);
absolutely unnecessary _ContentService_, _SPAMiddleware_ and middlewares
see: https://github.com/foxssake/dumber-dungeons/tree/show-off/no-need-content-service

2024-12-19 12:35 UTC, ocsi0520 commented on packages/server/src/main.ts
> +  const contentService = app.get(ContentService);
Talked about this in discord: for frontend routes we need to serve the index.html file.
Created different solution together.

2024-12-19 12:36 UTC, ocsi0520 commented on packages/server/src/view.service.ts
> +const packageRoot = resolve(join(import.meta.dir, '../'));
As mentioned in prev comment: ContentController provides index.html for FE routes

2024-12-19 12:37 UTC, elementbound commented on packages/server/src/main.ts
> +  const contentService = app.get(ContentService);
![image](https://github.com/user-attachments/assets/a22ef4a2-6c4c-47c2-adc4-925d6654fc04)

2024-12-19 12:38 UTC, merged