feat: Session management
foxssake/dumber-dungeons pull request #42
Opened 2024-12-04 16:28 UTC by elementbound

Closes #23

2024-12-04 16:50 UTC, elementbound commented on packages/server/src/session/session.module.ts
> +  providers: [SessionService, SessionDAO, IDGenerator],
Will move the IDGenerator to a utility module

2024-12-07 20:44 UTC, ocsi0520 requested changes

2024-12-07 20:44 UTC, ocsi0520 commented on packages/server/src/assert.ts
> +export function assert(condition: boolean, message: string = ''): void {
server-side we can use `node:assert`
https://bun.sh/docs/runtime/nodejs-apis

2024-12-07 20:44 UTC, ocsi0520 commented on packages/server/tsconfig.build.json
>  {
I got that, that we have a separate tsconfig only for build, where we can exclude the type-checks on
node_modules, test, dist, and test files, but where do we reference it?

2024-12-08 22:13 UTC, elementbound commented on packages/server/src/assert.ts
> +export function assert(condition: boolean, message: string = ''): void {
Done.

2024-12-08 22:13 UTC, elementbound commented on packages/server/tsconfig.build.json
>  {
IIIRC it's a leftover from nest's starter template. Removed, since we don't actually transpile server code.

2024-12-12 11:27 UTC, merged