feat: Lobby view
foxssake/dumber-dungeons pull request #43
Opened 2024-12-07 10:39 UTC by elementbound

Closes #25

2024-12-07 20:57 UTC, ocsi0520 commented on packages/client/tsconfig.json
> +      "@shared/*": [ "../shared/src/*" ]
Isn't `shared` a package? Why do you need paths then?
Just put `shared` as a relative package into package.json: https://stackoverflow.com/a/14387210

2024-12-07 21:08 UTC, ocsi0520 commented on packages/client/src/pageutils.ts
> +export function renderPage(
renderRootPage?

2024-12-07 21:08 UTC, ocsi0520 commented on packages/client/package.json
> +    "@dumber-dungeons/shared": "workspace:*",
:open_mouth:

2024-12-07 21:08 UTC, ocsi0520 commented on packages/client/public/style.css
> +.lobby__panel {
I'm begging you to not use BEM

2024-12-08 22:17 UTC, elementbound commented on packages/client/src/pageutils.ts
> +export function renderPage(
Why? There's only one active page at a time, the one that's opened. I don't see the point for distinction.

2024-12-08 22:18 UTC, elementbound commented on packages/client/public/style.css
> +.lobby__panel {
Begging accepted :smile: What should we use instead?

2024-12-12 11:10 UTC, ocsi0520 commented on packages/client/public/style.css
> +.lobby__panel {
**scss**

or

```css
.lobby .panel { ... }
/* or */
.lobby > .panel { .. }
```

2024-12-12 13:30 UTC, ocsi0520 commented on packages/client/src/views/lobby/lobby.tsx
> +  const [qrData, setQrData] = useState('foo');
Why didn't you use builtin `#toDataURL`?

```tsx
const [qrImage, setQrData] = useState<string | undefined>();
QR.toDataURL(link, { type: 'image/png' }).then(setQrData);
// ...
{ qrImage && <img src={qrImage} /> }  
```

2024-12-12 13:33 UTC, ocsi0520 commented on packages/client/src/views/lobby/lobby.tsx
> +              <td>{participant.isReady ? '✔️' : '❌'}</td>
isn't ✅ better? :smile: 
https://www.compart.com/en/unicode/U+2705

2024-12-12 21:14 UTC, elementbound commented on packages/client/src/session.ts
> +// TODO: Grab from some shared source
Will grab contact entities from `shared`.

2024-12-12 21:37 UTC, ocsi0520 commented on packages/client/tsconfig.json
> +      "@shared/*": [ "../shared/src/*" ]
root _package.json_:
```JSON
  "workspaces": ["packages/*"],
  "devDependencies": {
    "shared": "workspace:./packages/shared"
  }
```

client _package.json_:
```JSON
"dependencies": {
    "iti": "^0.7.0",
    "iti-react": "^0.7.0",
    "react": "19.0.0-rc.1",
    "react-dom": "^19.0.0",
    "three": "^0.170.0",
    "shared": "workspace:*"
  },
```

2024-12-16 21:41 UTC, elementbound commented on packages/client/tsconfig.json
> +      "@shared/*": [ "../shared/src/*" ]
Done! ( Will rebase if/once #46 is merged )

2024-12-16 21:41 UTC, elementbound commented on packages/shared/src/event.emitter.ts
> +  public add(handler: EventHandler<T>): void {
To remove is to skill issue ( added `remove()` )

2024-12-16 21:42 UTC, elementbound commented on packages/client/public/style.css
> +.lobby__panel {
Updated stylesheet to use whatever-as-long-as-not-BEM

2024-12-16 21:42 UTC, elementbound commented on packages/client/src/views/lobby/lobby.tsx
> +  const [qrData, setQrData] = useState('foo');
Nice catch! Updated.

2024-12-16 22:07 UTC, elementbound commented on packages/client/src/views/lobby/lobby.tsx
> +              <td>{participant.isReady ? '✔️' : '❌'}</td>
Updated to ✅/❎!

2024-12-16 22:08 UTC, elementbound commented on packages/client/src/views/lobby/lobby.tsx
> +  dungeonClient.onParticipantJoin.add(() => setParticipants(dungeonClient.getParticipants()));
Fixed!

I would prefer to emit these events separately, as subscribers need to know whether someone's joining or leaving. Just based off of the fact that the lobby doesn't have different behaviors, I wouldn't merge these three events, upon semantic considerations.

2024-12-16 22:08 UTC, elementbound commented on packages/client/src/session.ts
> +// TODO: Grab from some shared source
Done.

2024-12-16 22:36 UTC, elementbound commented
@ocsi0520 I've cleaned up the PR, let me know what you think! If you're ok with the general approach, I'll add tests.

2024-12-18 18:11 UTC, ocsi0520 requested changes

2024-12-18 18:11 UTC, ocsi0520 commented on packages/client/src/link.service.ts
> +  public parseLobby(url: URL): string | undefined {
Looking at the name, I'm not sure what I got back from the method.
TBH, after reading the whole method, I'm still not sure. Is it the sessionId?

In case yes, let's rename it to `getSessionIDFrom(lobbyURL: string): string | undefined`

2024-12-18 18:11 UTC, ocsi0520 commented on packages/client/src/index.tsx
> +app.items.router.render(new URL(window.location.href));
Don't we want to have a "static" root element where the inner content can change, but the element itself stays?
If not, then this index.tsx is rather a simple index.ts

2024-12-18 18:11 UTC, ocsi0520 commented on packages/client/src/router.ts
> +    const root = createRoot(rootElement);
so on every render we create a new root?

2024-12-18 18:11 UTC, ocsi0520 commented on packages/client/src/dungeon.client.ts
> +  private subscribeToEvents(): void {
Instead of listening to our own emission, why don't inject changes into socket subscription?
```typescript
  private subscribeToSocket(): void {
    this.socket.on('participant/join', (participant: Participant) => {
      this.addParticipant(participant);
      this.onParticipantJoin.emit({ participant });
    });
    this.socket.on('participant/update', (participant: Participant) => {
      this.updateParticipant(participant);
      this.onParticipantChange.emit({ participant });
    });
    this.socket.on('participant/leave', (participant: Participant) => {
      this.removeParticipant(participant);
      this.onParticipantLeave.emit({ participant });
    });
  }
```

2024-12-18 20:49 UTC, elementbound commented on packages/client/src/views/style.css
> +  max-width: 100vh;
The intent is to keep the content's vertical flow. So when the window is wider than it is tall, there's a column of content in the middle, and when the window is taller than wide, it will just take up the available space.

2024-12-18 20:49 UTC, elementbound commented on packages/client/src/template.html
> +  <base href="/" />
For endpoints like /lobby/<id> - without the base tag, relative URLs will reference assets and scripts at /lobby/ and get 404's.

2024-12-18 20:54 UTC, elementbound commented on packages/client/src/router.ts
> +    const root = createRoot(rootElement);
Currently, yes - though this render only happens once, on page load. But we can change it to cache the root and only create it once no matter how many times this method is called.

2024-12-18 20:55 UTC, elementbound commented on packages/client/src/dungeon.client.ts
> +  private subscribeToEvents(): void {
No strong feelings in either direction.

2024-12-19 13:57 UTC, elementbound commented on packages/client/src/router.ts
Agreed, will use react-router

2024-12-19 13:58 UTC, elementbound commented on packages/client/src/link.service.ts
> +  public joinLobby(sessionId: string): URL {
Hopefully we can remove this service, or most of it, after adding react-router

2024-12-19 13:58 UTC, elementbound commented on packages/client/src/link.service.ts
> +  public parseLobby(url: URL): string | undefined {
Will remove this after adding react-router.

2024-12-19 13:59 UTC, elementbound commented on packages/client/src/router.ts
> +    const root = createRoot(rootElement);
Will remove this after adding react-router.

2024-12-19 17:47 UTC, elementbound commented on packages/client/src/dungeon.client.ts
> +  private subscribeToEvents(): void {
Done.

2024-12-19 17:47 UTC, elementbound commented on packages/shared/src/api/index.ts
Removed.

2024-12-19 17:47 UTC, elementbound commented on packages/shared/src/api/participant.ts
> +export interface Participant {
Updated code.

2024-12-19 17:47 UTC, elementbound commented on packages/client/src/views/lobby/join.lobby.pane.tsx
> +import { app } from '../../app';
now absolute parent import

2024-12-19 18:36 UTC, elementbound commented on packages/client/src/router.ts
Done.

2024-12-19 18:37 UTC, elementbound commented on packages/client/src/router.ts
> +import type { ReactNode } from "react"
![image](https://github.com/user-attachments/assets/f51fc335-5457-44fc-bbd3-f786c14f292d)

2024-12-19 18:38 UTC, elementbound commented on packages/client/src/link.service.ts
> +  public joinLobby(sessionId: string): URL {
Removed.

2024-12-19 18:38 UTC, elementbound commented on packages/client/src/link.service.ts
> +  public parseLobby(url: URL): string | undefined {
Removed.

2024-12-19 18:39 UTC, elementbound commented on packages/client/src/index.tsx
> +app.items.router.render(new URL(window.location.href));
![image](https://github.com/user-attachments/assets/5a88c7cd-8bcf-455e-b350-164e14fa0b96)

2024-12-19 18:39 UTC, elementbound commented on packages/client/src/router.ts
> +    const root = createRoot(rootElement);
Removed.

2024-12-25 10:06 UTC, ocsi0520 approved these changes

2024-12-25 10:06 UTC, ocsi0520 commented on packages/client/src/views/error/error.view.tsx
> +export function ErrorView(props: { error: Error }): JSX.Element {
yep, I can see _FallbackProps_ is :hankey:

2024-12-25 10:16 UTC, elementbound commented on packages/client/src/components/style.tsx
> +export function Style(props: { href: string }): JSX.Element {
Good point. What do you think about `InjectedStyle`? Or alternatively just `Stylesheet`, since I'm inserting a stylesheet and don't really care what happens in the background.

2024-12-25 10:20 UTC, ocsi0520 commented on packages/client/src/components/style.tsx
> +export function Style(props: { href: string }): JSX.Element {
`InjectedStyle` is good, but also you are right about
> don't really care what happens in the background.

What about `ExternalStyle` since you have to know about its props, namely the _href_, therefore you know about it's an external one.

2024-12-25 10:22 UTC, elementbound commented on packages/client/src/components/style.tsx
> +export function Style(props: { href: string }): JSX.Element {
`ExternalStyle` it is!

2024-12-25 12:14 UTC, elementbound commented on packages/client/src/index.tsx
> +  document.body.appendChild(element);
Unviolated CQS

2024-12-25 12:14 UTC, merged