feat: Participant management
foxssake/dumber-dungeons pull request #45
Opened 2024-12-13 20:17 UTC by elementbound

Closes #24

2024-12-13 20:24 UTC, elementbound commented on packages/server/src/session/participant.ts
> +export interface Participant {
Will move this to `shared/src/api` in #43

2024-12-17 17:09 UTC, ocsi0520 commented on packages/server/src/utils/id.generator.ts
> +  public forParticipant(): string {
_JUST_MENTIONING_
Don't think we'll hit a problem with this structure, but TBH this feels like it knows more than it should.
Maybe the consumer should know about the length of its ID, or there should be a separate config for that.
'cause right now the IDGenerator knows its consumers.

Anyway it can stay as is.

2024-12-17 17:18 UTC, elementbound commented on packages/server/src/utils/id.generator.ts
> +  public forParticipant(): string {
My line of thinking is that these ID's are opaque, i.e. whenever I request an ID I don't care about its structure or length. This is how the knowledge of how long each ID type has landed in IDGenerator.

But I agree that eventually it would be great to make it configurable.

2024-12-17 17:51 UTC, ocsi0520 requested changes

2024-12-17 17:51 UTC, ocsi0520 commented on packages/server/src/session/participant.dao.ts
> +export class ParticipantDAO extends BaseDAO<Participant, string> {}
_optional_
I should have mentioned that before, but BaseDAO could be simply DAO.
I don't remember which RCM (Robert C. Martin) video I saw that we should not have any prefixes like `Base`, `I`, `Abstract`.

2024-12-17 17:51 UTC, ocsi0520 commented on packages/server/src/session/session.controller.ts
> +  ): Promise<Participant | undefined> {
I'd prefer to have return type as `Promise<Participant>`
If for some reason we can't provide a 'Participant', we should throw the appropriate HTTP error

2024-12-17 17:51 UTC, ocsi0520 commented on packages/server/src/session/session.service.ts
> +    assert(
I got that the previous check (hasSession) is basically an assert, whether the consumer found a living session,
but this one is rather an error check IMHO.

The consumer (SessionController) can't verify whether the found living session is in good state or not, therefore it's the responsibility of the SessionService.
As a result, it's not a presumption, but a requirement.

2024-12-17 17:51 UTC, ocsi0520 commented on packages/server/src/session/session.service.ts
> +    await this.sessionDAO.save(session);
This is a rather theoretical question, but what happens if the save of the participant is done, but for some reason session save has failed? We got a fractured/inconsistent state.
My point is here, that we don't express the part-whole connection between them, plus we don't have any transaction-like mechanism.

We should talk about this.

2024-12-17 17:51 UTC, ocsi0520 commented on packages/server/src/session/session.service.ts
> +  ): Promise<Participant> {
IDK whether we can solve it, but this method violates CQS principle.
Maybe an ideal solution from the consumer:
```typescript
const session = this.sessionService.find(sessionId);
const participant = this.sessionService.createParticipant(participantOptions);
session.join(participant);
this.sessionService.save(session);
```

2024-12-19 13:03 UTC, elementbound commented on packages/server/src/session/session.service.ts
> +    assert(
Will call it `verify` to reflect the above.

2024-12-19 13:40 UTC, elementbound commented on packages/server/src/session/session.service.ts
> +    await this.sessionDAO.save(session);
![image](https://github.com/user-attachments/assets/78387309-2f97-4ecb-8a84-d9ddf748cfa5)

2024-12-19 13:41 UTC, ocsi0520 approved these changes

2024-12-19 13:43 UTC, merged